# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # # Permissions for this workflow.
    # permissions:
    #   contents: read
    #   pages: write
    # FIXME: This does not work, you have to give read and write permissions for the workflows
    #        of the repository in Settings > Actions > General > Workflow permissions.
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: .
          root_file: about-Fourier-optics.tex
      - run: sudo apt-get -y install pdf2svg
      - run: |
          pdf2svg about-Fourier-optics.pdf about-Fourier-optics.svg 1
          mkdir pdf
          mv *{.svg,.pdf} pdf/.
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdf
          force_orphan: true
